//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bluebean.ConfigData {
    
    
    [System.SerializableAttribute()]
    public class ConfigDataConst {
        
        private int m_ID;
        
        private string m_TypeEnum;
        
        private int m_Value;
        
        private string m_StrValue;
        
        public int ID {
            get {
                return this.m_ID;
            }
            set {
                this.m_ID = value;
            }
        }
        
        public string TypeEnum {
            get {
                return this.m_TypeEnum;
            }
            set {
                this.m_TypeEnum = value;
            }
        }
        
        public int Value {
            get {
                return this.m_Value;
            }
            set {
                this.m_Value = value;
            }
        }
        
        public string StrValue {
            get {
                return this.m_StrValue;
            }
            set {
                this.m_StrValue = value;
            }
        }
    }
    
    public enum ConfigDataConstType {
        
EndoscopeRadius = 1,
FourdirLength = 2,
FourdirJointCount = 3,
    }
    
    [System.SerializableAttribute()]
    public class ConfigDataCourse {
        
        private int m_ID;
        
        private string m_Name;
        
        private string m_Desc;
        
        private int m_CourseType;
        
        private int m_Param1;
        
        private int m_Param2;
        
        private int m_Param3;
        
        private int m_EndoscopeConfigID;
        
        private string m_ScenePrefab;
        
        private string m_LevelPrefab;
        
        private System.Collections.Generic.List<System.Int32> m_InitLoadedInstruments;
        
        private string m_InputManagerPrefab;
        
        public int ID {
            get {
                return this.m_ID;
            }
            set {
                this.m_ID = value;
            }
        }
        
        public string Name {
            get {
                return this.m_Name;
            }
            set {
                this.m_Name = value;
            }
        }
        
        public string Desc {
            get {
                return this.m_Desc;
            }
            set {
                this.m_Desc = value;
            }
        }
        
        public int CourseType {
            get {
                return this.m_CourseType;
            }
            set {
                this.m_CourseType = value;
            }
        }
        
        public int Param1 {
            get {
                return this.m_Param1;
            }
            set {
                this.m_Param1 = value;
            }
        }
        
        public int Param2 {
            get {
                return this.m_Param2;
            }
            set {
                this.m_Param2 = value;
            }
        }
        
        public int Param3 {
            get {
                return this.m_Param3;
            }
            set {
                this.m_Param3 = value;
            }
        }
        
        public int EndoscopeConfigID {
            get {
                return this.m_EndoscopeConfigID;
            }
            set {
                this.m_EndoscopeConfigID = value;
            }
        }
        
        public string ScenePrefab {
            get {
                return this.m_ScenePrefab;
            }
            set {
                this.m_ScenePrefab = value;
            }
        }
        
        public string LevelPrefab {
            get {
                return this.m_LevelPrefab;
            }
            set {
                this.m_LevelPrefab = value;
            }
        }
        
        public System.Collections.Generic.List<System.Int32> InitLoadedInstruments {
            get {
                return this.m_InitLoadedInstruments;
            }
            set {
                this.m_InitLoadedInstruments = value;
            }
        }
        
        public string InputManagerPrefab {
            get {
                return this.m_InputManagerPrefab;
            }
            set {
                this.m_InputManagerPrefab = value;
            }
        }
    }
    
    public enum ConfigDataCourseType {
        
Inject = 1,
Biopsy = 2,
Cutting = 3,
Inspect = 4,
Inserting = 5,
    }
    
    [System.SerializableAttribute()]
    public class ConfigDataEndoscope {
        
        private int m_ID;
        
        private string m_Name;
        
        private string m_Desc;
        
        private string m_Prefab;
        
        private System.Collections.Generic.List<System.Int32> m_CameraDummyPos;
        
        private System.Collections.Generic.List<System.Int32> m_CameraDummyRotation;
        
        private System.Collections.Generic.List<System.Int32> m_OperateDeviceDummyPos;
        
        private System.Collections.Generic.List<System.Int32> m_OperateDeviceDummyRotation;
        
        public int ID {
            get {
                return this.m_ID;
            }
            set {
                this.m_ID = value;
            }
        }
        
        public string Name {
            get {
                return this.m_Name;
            }
            set {
                this.m_Name = value;
            }
        }
        
        public string Desc {
            get {
                return this.m_Desc;
            }
            set {
                this.m_Desc = value;
            }
        }
        
        public string Prefab {
            get {
                return this.m_Prefab;
            }
            set {
                this.m_Prefab = value;
            }
        }
        
        public System.Collections.Generic.List<System.Int32> CameraDummyPos {
            get {
                return this.m_CameraDummyPos;
            }
            set {
                this.m_CameraDummyPos = value;
            }
        }
        
        public System.Collections.Generic.List<System.Int32> CameraDummyRotation {
            get {
                return this.m_CameraDummyRotation;
            }
            set {
                this.m_CameraDummyRotation = value;
            }
        }
        
        public System.Collections.Generic.List<System.Int32> OperateDeviceDummyPos {
            get {
                return this.m_OperateDeviceDummyPos;
            }
            set {
                this.m_OperateDeviceDummyPos = value;
            }
        }
        
        public System.Collections.Generic.List<System.Int32> OperateDeviceDummyRotation {
            get {
                return this.m_OperateDeviceDummyRotation;
            }
            set {
                this.m_OperateDeviceDummyRotation = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public class ConfigDataInsertCourse {
        
        private int m_ID;
        
        private string m_Name;
        
        private string m_Desc;
        
        private string m_BubbleUIPrefab;
        
        private int m_BubbleSpeed;
        
        private int m_ScoreWeight4Time;
        
        private int m_ScoreWeight4Accuracy;
        
        private System.Collections.Generic.List<System.Int32> m_ScoreRankRange;
        
        private System.Collections.Generic.List<System.Int32> m_Params4TimeScore;
        
        public int ID {
            get {
                return this.m_ID;
            }
            set {
                this.m_ID = value;
            }
        }
        
        public string Name {
            get {
                return this.m_Name;
            }
            set {
                this.m_Name = value;
            }
        }
        
        public string Desc {
            get {
                return this.m_Desc;
            }
            set {
                this.m_Desc = value;
            }
        }
        
        public string BubbleUIPrefab {
            get {
                return this.m_BubbleUIPrefab;
            }
            set {
                this.m_BubbleUIPrefab = value;
            }
        }
        
        public int BubbleSpeed {
            get {
                return this.m_BubbleSpeed;
            }
            set {
                this.m_BubbleSpeed = value;
            }
        }
        
        public int ScoreWeight4Time {
            get {
                return this.m_ScoreWeight4Time;
            }
            set {
                this.m_ScoreWeight4Time = value;
            }
        }
        
        public int ScoreWeight4Accuracy {
            get {
                return this.m_ScoreWeight4Accuracy;
            }
            set {
                this.m_ScoreWeight4Accuracy = value;
            }
        }
        
        public System.Collections.Generic.List<System.Int32> ScoreRankRange {
            get {
                return this.m_ScoreRankRange;
            }
            set {
                this.m_ScoreRankRange = value;
            }
        }
        
        public System.Collections.Generic.List<System.Int32> Params4TimeScore {
            get {
                return this.m_Params4TimeScore;
            }
            set {
                this.m_Params4TimeScore = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public class ConfigDataInstruments {
        
        private int m_ID;
        
        private int m_Type;
        
        private string m_Name;
        
        private string m_Desc;
        
        private string m_Prefab;
        
        private int m_SlotID;
        
        public int ID {
            get {
                return this.m_ID;
            }
            set {
                this.m_ID = value;
            }
        }
        
        public int Type {
            get {
                return this.m_Type;
            }
            set {
                this.m_Type = value;
            }
        }
        
        public string Name {
            get {
                return this.m_Name;
            }
            set {
                this.m_Name = value;
            }
        }
        
        public string Desc {
            get {
                return this.m_Desc;
            }
            set {
                this.m_Desc = value;
            }
        }
        
        public string Prefab {
            get {
                return this.m_Prefab;
            }
            set {
                this.m_Prefab = value;
            }
        }
        
        public int SlotID {
            get {
                return this.m_SlotID;
            }
            set {
                this.m_SlotID = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public class ConfigDataInstrumentsSlot {
        
        private int m_ID;
        
        private string m_Name;
        
        private string m_Desc;
        
        private int m_OffsetX;
        
        private int m_OffsetY;
        
        public int ID {
            get {
                return this.m_ID;
            }
            set {
                this.m_ID = value;
            }
        }
        
        public string Name {
            get {
                return this.m_Name;
            }
            set {
                this.m_Name = value;
            }
        }
        
        public string Desc {
            get {
                return this.m_Desc;
            }
            set {
                this.m_Desc = value;
            }
        }
        
        public int OffsetX {
            get {
                return this.m_OffsetX;
            }
            set {
                this.m_OffsetX = value;
            }
        }
        
        public int OffsetY {
            get {
                return this.m_OffsetY;
            }
            set {
                this.m_OffsetY = value;
            }
        }
    }
    
    public enum ConfigDataInstrumentsType {
        
InjectionNeedle = 1,
Light = 2,
BiopsyForceps = 3,
ElectrosurgicalKnife = 4,
    }
    
    [System.SerializableAttribute()]
    public class ConfigDataSound {
        
        private int m_ID;
        
        private string m_StrKey;
        
        private int m_Volume;
        
        private string m_Path;
        
        public int ID {
            get {
                return this.m_ID;
            }
            set {
                this.m_ID = value;
            }
        }
        
        public string StrKey {
            get {
                return this.m_StrKey;
            }
            set {
                this.m_StrKey = value;
            }
        }
        
        public int Volume {
            get {
                return this.m_Volume;
            }
            set {
                this.m_Volume = value;
            }
        }
        
        public string Path {
            get {
                return this.m_Path;
            }
            set {
                this.m_Path = value;
            }
        }
    }
}
